---
title: "Internet, Education and Development"
output: html_document
bibliography: Biblio.bib
---

## Assignment 2
```{r}
library(bibtex)
```
A (max) 2,000 word proposal created with R Markdown.
The proposal will:
* Be written in R Markdown.
* State your research question. And justify why it is interesting.
* Provide a basic literature review (properly cited with BibTeX).
* Identify data sources and appropriate research methodologies for answering your question.

##Research Question 
<<<<<<< HEAD
Our researching question is based on whether the Internet accesibility rate has a direct impact on the students academic ability and the economic growth. Currently, it can be argued that not having a proper Internet accessibility can decrease the potencial of the students when learning. Moreover, this can also be harmful for the GDP growth, because future generations will not be prepared to apply new technologies and, therefore, losing the chance to apply one of the most efficient methods to produce benefits.(see @beldarrain2006distance)

Currently, it can be argued that not having a proper Internet accessibility can decrease the potencial of the students when learning. On the other hand, there is another argument that the easy internet accessiblity could deprive the creativeness of students. There, we will analyze the correlation between **internet accesibility**, **education system** and **student's academic record**.

Moreover, there is an argument that despite all the benefits of new technologies, internet might bring a negative effect on people's morality and politics, as a result it is negative rather than a positive influence on the national long-term growth. However, not having proper Internet accessibility  can also be harmful for the GDP growth, because future generations will not be prepared to apply new technologies and, therefore, losing the chance to apply one of the most efficient methods to produce benefits.
>>>>>>> origin/master

##Hypothesis
Our hypothesis is that **Internet accessibility is beneficial for both student's academic record and economic growth**.

##Basic Literature Review
<<<<<<< Updated upstream
**Internet Seen as Positive Influence on Education but Negative on Morality in Emerging and Developing Nations** (Reference3 @PewReserchCenter)

This report is analyzing "technology use in 32 emerging and developing nations, including internet access rates, and cell phone and smartphone ownership. It also examines internet and mobile activities, as well as public opinion regarding the internet’s impact on society."(@PewReserchCenterp1)
This report cast doubt on the idea that Internet will bring a bad effect on the nation's long-term growth because it could be harmful on morality of people.
According to the report, the result is different between developing and developed countries. Internet access brought a positive influence of education of clear majority of people in emerging and developing countries. On the other hands, only 36% people say it is a lositive for thieir country's politicial system, while three-in-ten say it is a bad influence in emerging and developing countries. In addition, people are even more leery of the inernet's efect on morality, ane 42% day it is a bad influence.

**Expanding Internet access to the rural poor in Africa**

<<<<<<< HEAD
This report is about the Internet accessibility in Africa. Internet has the potential to play a significant role in reducing poverty and promoting sustainable development, especially in rural areas. The paper argues that liberalization of the telecommunications sector combined with targeted, auctioned subsidies to local entrepreneurs are both likely to have a significant impact on rural Internet access rates and poverty. (see @kenny2000expanding)
=======
At present, the Internet is little used in Africa. However, it has the potential to play a significant role in reducing poverty and promoting sustainable development, especially in rural areas. This paper examines two important elements of increasing rural Internet access: reducing costs of Internet service provision and increasing the number of rural access points. The paper argues that liberalization of the telecommunications sector combined with targeted, auctioned subsidies to local entrepreneurs are both likely to have a significant impact on rural Internet access rates. (see @kenny2000expanding)
=======
* **Internet Seen as Positive Influence on
Education but Negative on Morality in
Emerging and Developing Nations** (Reference3 @poushter2015internet)

This report is analyzing "technology use in 32 emerging and developing nations, including internet access rates, and cell phone and smartphone ownership. It also examines internet and mobile activities, as well as public opinion regarding the internet’s impact on society."(@poushter2015internet)
This report cast doubt on the idea that Internet will bring a good effect on the nation's long-term growth because it could be harmful on morality of people. 
Also, this report implied that the result would be differebt between emarging/developing countries and developed countries. Internet access brought a positive influence of education of clear majority of people in emerging and developing countries. On the other hands, only 36% people say it is a lositive for thieir country's politicial system, while three-in-ten say it is a bad influence in emerging and developing countries. In addition, people are even more leery of the inernet's efect on morality, ane 42% day it is a bad influence. However, this report concludes that across the emerging and develoving nations surveyed, internet access is closely linked to national income.

Therefore, we would like to compare the impact of internet access on eduactio and economy by devideng countries to two groups (emerging/depeloping countries and developed countries.)
>>>>>>> Stashed changes
>>>>>>> origin/master

##Data Sources and Methodologie
###Data Sources
We will refer "World DataBank" and Central Intelligence agency(CIA)'s "Factbook" and  use datas. Likewise, we also will use the "QOG dataset 2016." A recopilation of data made by the University of Gothenburg. We will use data on education and internet infrastructure.
Internet Users (CIA): https://www.cia.gov/library/publications/resources/the-world-factbook/fields/2153.html#xx
QOG Data: http://qog.pol.gu.se/data/datadownloads/qogstandarddata
World DataBank (WDI): http://databank.worldbank.org/data/home.aspx

###Methodologie
<<<<<<< Updated upstream
<<<<<<< Updated upstream
Our methodologie will be based on data on ***Internet Accesibiity***, ***Qualith of Education System***, ***Average Schooling Years***, and ***GDP Growth Rate*** of all the countries. Then we will analyze the correlation between them in order to answer our researching question. 
Our research will be quantitative. Quantitative methods emphasize objective measurements and the statistical, mathematical, or numerical analysis of data collected through polls, questionnaires, and surveys, or by manipulating pre-existing statistical data using computational techniques. This quantitative research will focus on gathering numerical data and generalizing it across groups of people or to explain how influential is the Internet accessibility when improving education and growth.
=======
Our methodologie will be based on data on **Internet Accesibiity**, **Qualith of Education System**, **Average Schooling Years**, and **GDP Growth Rate** of all the countries. Then we will analyze the correlation between them in order to answer our researching question. 
Our research will be quantitative. Quantitative methods emphasize objective measurements and the statistical, mathematical, or numerical analysis of data collected through polls, questionnaires, and surveys, or by manipulating pre-existing statistical data using computational techniques. This quantitative research will focus on gathering numerical data and generalizing it across groups of people or to explain how influential is the internet accessibility when improving education and growth.
>>>>>>> Stashed changes
=======
Our methodologie will be based on data on **Internet Accesibiity**, **Quality of Education System**, **Average Schooling Years**, and **GDP Growth Rate** of all the countries. Then we will analyze the correlation between them in order to answer our researching question.
>>>>>>> Stashed changes

Reference
=======

